### ISSUE TITLE
Foro de la Tarea 2

### ISSUE THREAD

**Issue by domingomery** [domingomery/imagenes#10]
Preguntas sobre la Tarea 2: Antes de hacer la pregunta revisar bien el enunciado de la Tarea y revisar si la duda que tienes no fue aclarada en clases. Gracias!

**Comment by fprebolledo** [comment]
Hola profesor, resspecto al enunciado de la t2 dice: "El programa debe ser el mismo para cada imagen, sin embargo, los parametros pueden ser distintos y pueden ser fijados manualmente para cada una de las imagenes. Con este fin disene una funcion que se llame FiltroTarea2 que reciba como entrada la imagen ruidosa 'X' y los n parametros p1, p2, ... pn, de esta manera se ejecuta Y = FiltroTarea2(X,p1,p2,..,pn) para obtener la imagen de salida 'Y'."  Con parámetros se refiere a cualquier cosa que necesitemos para los filtros? o es algo específico?
gracias.

**Comment by domingomery** [comment]
La solucion debe ser un solo algoritmo, pero con distintos parametros. Por ejemplo si el algoritmo consiste en aclarar la imagen (multiplicandola por un factor k), hacer la transformada de Fourier, hacer un filtro pasa bajos (con frecuencia de corte w) y hacer la transformada inversa, entonces tu funcion debe ser Y = FiltroTarea2(X,k,w). La idea es que la imagen 1 tenga parametros k1,w1, la imagen 2, parametros k2,w2, etc... un mismo algoritmo, pero con distintos parametros. En la solucion uds. deben indicar cuales son los mejores parametros necesarios para cada una de las imagenes, y los parametros pueden encontrarlos de manera manual.

 **OJO:** Lo que no es un parametro de ninguna manera es definir un numero i y que sirva para identificar a la imagen i y hacer algo especifico para la imagen i, es decir, if i==1 entonces hago el algoritmo de la imagen 1, if i==2 hago el agoritmo para la imagen 2... etc.

**Comment by dabalada** [comment]
Hola, importa el tiempo de ejecucion del algoritmo? y al comparar el resultado obtenido con la imagen original sin ruido, si el resultado obtenido es mas claro o mas obscuro que la imagen original, afectará el error promedio?

**Comment by domingomery** [comment]
Buen punto! En la corrección, antes de calcular el error, cada imagen
será escalada linealmente (de esta forma el mínimo será cero y el maximo
será 255). Saludos

**Comment by fprebolledo** [comment]
Entonces respecto a los parámetros podría ser por ej las coordenadas de fourier que quiero eliminar? y pasarlas al filtro? o eso debería calcularlo dentro del algoritmo y que el parámetro sea por ejemplo, el radio que voy a eliminar desde el centro de cada pixel?
GRacias.

**Comment by domingomery** [comment]
asi es, las frecuencias de Fourier necesarias, anchos del filtro, etc.
pueden ser parametros de tu algoritmo...  estos parametros los puedes
calcular de forma manual...saludos

**Comment by fprebolledo** [comment]
Hola profesor, me preguntaba si usted podría subir algunas imagenes modelo de output para esta tarea, como vimos en clases, los filtros pasabajos dejan las imagenes algo borrosas y me gustaría saber como cuales son los "límites" de esto.

**Comment by domingomery** [comment]
prefiero no dar las imagenes modelo para evitar que se haga ingeniería
inversa... créeme que lo siento mucho....

**Comment by cerealnuee** [comment]
¡Hola! Entonces con "distinto algoritmo" ¿se podría entender "distinto filtro"? Porque probé con un filtro ideal cuadrado y con un filtro gaussiano, y en 1 caso uno de los filtros me dio un mejor resultado que el otro. Pensaba hacer algún argumento para la función estilo "mode" en que puede ser mode = 'gauss' o mode = 'ideal', pero siento que eso estaría rozando en el límite de lo permitido

**Comment by fprebolledo** [comment]
Hola, una consulta. Importa más quitar todo el ruido de la imagen o que la imagen tenga la mejor calidad que se pueda? Me pasa que si elimino ciertos puntos me queda ruido en los bordes, pero en general la imagen se ve bien, sin embargo si elimino algunos otros más se quita la mayoría de los bordes, pero comienzan a aparecer estos anillos que se mencionaron en clases, intenté disminuirlos lo más que pude, pero no me ha resultado mucho. Recomendaría más dejar la imagen con mejor calidad o con menos ruido?

**Comment by domingomery** [comment]
> ¡Hola! Entonces con "distinto algoritmo" ¿se podría entender "distinto filtro"? Porque probé con un filtro ideal cuadrado y con un filtro gaussiano, y en 1 caso uno de los filtros me dio un mejor resultado que el otro. Pensaba hacer algún argumento para la función estilo "mode" en que puede ser mode = 'gauss' o mode = 'ideal', pero siento que eso estaría rozando en el límite de lo permitido

OK, se permite... es decir se permite un parámetro que tenga que ver con la forma del filtro.

**Comment by domingomery** [comment]
> Hola, una consulta. Importa más quitar todo el ruido de la imagen o que la imagen tenga la mejor calidad que se pueda? Me pasa que si elimino ciertos puntos me queda ruido en los bordes, pero en general la imagen se ve bien, sin embargo si elimino algunos otros más se quita la mayoría de los bordes, pero comienzan a aparecer estos anillos que se mencionaron en clases, intenté disminuirlos lo más que pude, pero no me ha resultado mucho. Recomendaría más dejar la imagen con mejor calidad o con menos ruido?

es mejor optar por la opción que entregue una imagen de mejor calidad, aunque los bordes se vean con ruido. Saludos
