### ISSUE TITLE
Tarea 01 - Imágenes

### ISSUE THREAD

**Issue by domingomery** [domingomery/imagenes#12]
Por favor hacer comentarios aquí. Respondo todas las preguntas siempre y cuando no las haya aclarado en clases, o no estén escritas en el enunciado de la Tarea, o no las haya contestado en este foro. Usemos el foro responsablemente para que sea de utilidad. Preguntas repetidas, pueden hacer este foro excesivamente largo, lo que dificultará su lectura. Muchas gracias! Domingo

**Comment by jtcaraball** [comment]
Hola profesor, puedo usar la librería urllib para poder cargar las imágenes desde este repositorio? Adjunto el [link](https://stackoverflow.com/questions/2467609/using-wget-via-python) donde encontré la solución.

**Comment by domingomery** [comment]
Buen dato, pero prefiero no abrir la posibilidad de usar otras librerías, es decir solo se pueden usar las librerías del enunciado. Para subir las fotos a Google Colab puedes usar estos comandos:

`!wget https://www.dropbox.com/s/zq1pzhya4dues3o/imagenes.zip`

`!unzip imagenes.zip`

Las imágenes quedan cargadas en la carpeta `imagenes`.

**Comment by domingomery** [comment]
Está permitido usar la librería `matplotlib` para hacer gráficas o desplegar resultados...

**Comment by jtcaraball** [comment]
Hola profesor! Hay algún tiempo maximo de ejecución del programa? Actualmente logro encontrar la hora de todas las imagenes pero se demora al rededor de 3 minutos por imagen 😅

**Comment by domingomery** [comment]
> Hola profesor! Hay algún tiempo maximo de ejecución del programa? Actualmente logro encontrar la hora de todas las imagenes pero se demora al rededor de 3 minutos por imagen 😅. Creo que se debe a los pocos recursos que debe entregar google colab por que en mi computador el programa corre más rapido.

no es problema, lo ideal es no pasar los 5 minutos por imagen, por consideración a lo/as ayudantes.

**Comment by bdelsolar** [comment]
Hola! Respecto al informe, se pueden colocar fotos como parte de un anexo, sin que sean consideradas parte de la extensión máxima de 1 página? Son imágenes altas pero delgadas, entonces ocupan mucho espacio.

**Comment by domingomery** [comment]
> ... se pueden colocar fotos como parte de un anexo, sin que sean consideradas parte de la extensión máxima de 1 página?

El informe no debe ser de más de una página. Te recomiendo usar figuras intermedias en el mismo Colab, y hacer referencias a ellas en el informe. Saludos. Domingo

**Comment by bdelsolar** [comment]
Gracias! Otra duda, los archivos a entregar deben tener algún nombre particular? Se entrega en zip, por separado, o da lo mismo?

**Comment by domingomery** [comment]
se debe subir un solo archivo en formato ipynb, esto es el Colab que hagas para la tarea. Este archivo debe hacer todo, cargar las imagenes, procesarlas y entregar los resultados.

**Comment by domingomery** [comment]
CORRECCIÓN: 

> se debe subir un solo archivo en formato ipynb, esto es el Colab que hagas para la tarea. Este archivo debe hacer todo, cargar las imagenes, procesarlas y entregar los resultados.

CORRECCIÓN: se debe subir además el PDF con el informe, es decir deben subir dos archivos.

**Comment by Jaluco** [comment]
Hola, cual es la exactitud que se espera de los minutos, tramos de 5 minutos estan bien?

**Comment by domingomery** [comment]
> Hola, cual es la exactitud que se espera de los minutos, tramos de 5 minutos estan bien?

Se espera que puedas medir el ángulo de las manecillas, con esa información es simple obtener una resolución en tramos de 1 minuto. Saludos

**Comment by StroveLight** [comment]
Hola, pregunto si se pueden usar tipos de datos de python que ya bienen en los ```built-in```, en particular el uso de 
```from collections import deque``` para importar el tipo de dato cola. Esto lo pido ya que con una lista el tiempo de ejecución aumenta demasiado comparado con el uso de [deque](https://docs.python.org/3/library/collections.html#collections.deque)

**Comment by domingomery** [comment]
> Por favor hacer comentarios aquí. Respondo todas las preguntas siempre y cuando no las haya aclarado en clases, o no estén escritas en el enunciado de la Tarea, o no las haya contestado en este foro. Usemos el foro responsablemente para que sea de utilidad. Preguntas repetidas, pueden hacer este foro excesivamente largo, lo que dificultará su lectura. Muchas gracias! Domingo

Hacer las preguntas en el foro de Canvas que ya ha sido habilitado.

**Comment by Mario-uc** [comment]
Profesor se pueden usar páginas para visualizar los valores de RGB de ciertos puntos de la imagen para así tener una idea de que valores puedo usar para el umbral? O eso también lo tengo que hacer con código?

**Comment by domingomery** [comment]
> Profesor se pueden usar páginas para visualizar los valores de RGB de ciertos puntos de la imagen para así tener una idea de que valores puedo usar para el umbral? O eso también lo tengo que hacer con código?

Hacer las preguntas en el foro de Canvas que ya ha sido habilitado.
