### ISSUE TITLE
Foro de la Tarea 1

### ISSUE THREAD

**Issue by domingomery** [domingomery/imagenes#5]
Preguntas sobre la Tarea 1: Antes de hacer la pregunta revisar bien el enunciado de la Tarea y revisar si la duda que tienes no fue aclarada en clases. Gracias!

**Comment by caespinoza5** [comment]
Hola, tengo dos preguntas:

1. ¿El algoritmo debe necesariamente seguir los pasos i), ii), iii), iv) y v) del enunciado? Creo que hay más formas de desarrollar el algoritmo que me gustaría saber si puedo realizar.

2. La salida ¿En qué formato debe estar? ¿Puedo simplemente imprimir al final de mi programa `H=7,M=51`?

¡Gracias!

**Comment by jvlara** [comment]
Hola,
Segun entendi en la clase no podemos utilizar metodos que detecten circulos, por lo tanto, ¿Qué tecnicas se pueden utilizar para detectar bordes y luego la figura del circulo?

**Comment by domingomery** [comment]
> 1. ¿El algoritmo debe necesariamente seguir los pasos i), ii), iii), iv) y v) del enunciado? Creo que hay más formas de desarrollar el algoritmo que me gustaría saber si puedo realizar.

Es una sugerencia, no es una obligación seguir estos pasos.

> 2. La salida ¿En qué formato debe estar? ¿Puedo simplemente imprimir al final de mi programa `H=7,M=51`?

Por favor agregar el error entre lo que dice tu algoritmo y la hora real del reloj (el error son dos valores, la diferencia en las horas, y la diferencia en los minutos)

**Comment by domingomery** [comment]
> Segun entendi en la clase no podemos utilizar metodos que detecten circulos, por lo tanto, ¿Qué tecnicas se pueden utilizar para detectar bordes y luego la figura del circulo?

Asi es, no se puede usar librerias que detecten lineas (como Transformada Hough) o que detecten circulos. A menos que quieran uds. mismos implementar estas transformadas, para esto deben entender lo que es la Transformada Hough (esto lo veremos más adelante en el curso, como a mitad de semestre).

Las técnicas a usar se les tiene que ocurrir a ustedes, eso es parte de la tarea. Es fácil detectar el reloj (parte oscura de la imagen), de ahí detectar dónde está la zona blanca (es decir el reloj mismo), luego el centro de la zona blanca y hacer un barrido radial (que pase por el centro) detectando de esta manera las manecilas, etc. Son ideas que pueden emplear, obviamente, pueden usar otras estrategias...

**Comment by caespinoza5** [comment]
¿Está permitido usar funciones que roten imágenes?

**Comment by domingomery** [comment]
si, esta permitido usar funciones de rotacion y transformaciones
geometricas. Saludos

**Comment by cerealnuee** [comment]
¡Hola! Si decido escribir mi código en Python, ¿puedo entregar un archivo .ipynb o debe ser necesariamente .py?

¡Saludos!

**Comment by domingomery** [comment]
no hay problema con usar jupyter nootbooks (en formato ipynb). Saludos

**Comment by francisca1** [comment]
está permitido usar  cv2.morphologyEx() para quitar el ruido de la imagen?

**Comment by domingomery** [comment]
sip, se puede usar, siempre y cuando sepas como funciona para que puedas
explicarlo en el informe. Saludos

**Comment by domingomery** [comment]
no se puede usar tecnicas de Machine Learning, la idea es que te
familiarices con las tecnicas de procesamiento de imagenes. Saludos.

**Comment by domingomery** [comment]
en la tarea pueden usar el comando label de Python (o bien el comando
bwlabel de Matlab), no está permitido usar librerias de segmentación como
la de Otsu. Saludos.

**Comment by dabalada** [comment]
> > 1. ¿El algoritmo debe necesariamente seguir los pasos i), ii), iii), iv) y v) del enunciado? Creo que hay más formas de desarrollar el algoritmo que me gustaría saber si puedo realizar.
> 
> Es una sugerencia, no es una obligación seguir estos pasos.
> 
> > 1. La salida ¿En qué formato debe estar? ¿Puedo simplemente imprimir al final de mi programa `H=7,M=51`?
> 
> Por favor agregar el error entre lo que dice tu algoritmo y la hora real del reloj (el error son dos valores, la diferencia en las horas, y la diferencia en los minutos)

No me quedo clara la respuesta de la segunda pregunta. Cual es la hora que debo considerar como la correcta para calcular el error? y ese error también debo imprimirlo en pantalla junto a la hora leida?

algo como  "H = 7, M=51, Error_H = 0, Error_M =3"?

**Comment by domingomery** [comment]
> No me quedo clara la respuesta de la segunda pregunta. Cual es la hora que debo considerar como la correcta para calcular el error? y ese error también debo imprimirlo en pantalla junto a la hora leida?
> 
> algo como "H = 7, M=51, Error_H = 0, Error_M =3"?

Si, algo así es está bien

**Comment by dabalada** [comment]
y la hora de referencia puede ser introducida por el usuario al inicio del programa?

**Comment by domingomery** [comment]
como quieras, pero te sale mas fácil que tu mismo programa a partir del nombre del archivo de la imagen “sepa" cual es la hora ideal.

Saludos

**Comment by PanchitoHrndz** [comment]
Profesor, podemos ocupar el comando regionprops para encontrar el centro de un objeto?

**Comment by domingomery** [comment]
nop, la función 'regionprops' no se puede usar... el centro del objeto
debes computarlo como el centro de masa, es decir el promedio de la
coordenada i y el promedio de la coordenada j de todos los pixeles (i,j)
que pertenecen al objeto. Saludos.

**Comment by jhofmannl** [comment]
profesor, puede subir un par de fotos mas solo para ver si el codigo funciona?

**Comment by Matias-CT** [comment]
Hola, si estoy usando un notebook de Python como Jupyter ¿incluyo en mi código ciertos módulos donde explique los métodos que usé para segmentar, detectar las manecillas, etc. y luego al final en un último módulo decir 'por lo tanto está es la función' compilando todo el código anterior de manera de que haya un input imagen que entre y salga el output requerido, que es la medición de la hora más el error? en resumen ¿ es recomendable/necesario poner todos los métodos al principio del notebook y al final la solución como un único código?

**Comment by xDanman** [comment]
Profesor, es posible entregar dos archivos .m, uno con la solución y otro con código para generar figuras y así entender mejor el algoritmo?

**Comment by domingomery** [comment]
si, es posible, no hay problema

**Comment by domingomery** [comment]
si, es una buena idea poner primero las funciones y luego al final la
solucion que llama a estas funciones.

**Comment by domingomery** [comment]
no tengo mas fotos, y si tomo nuevas fotos no van quedar con la misma
iluminación, además no es la idea, el programa que diseñen debe funcionar
con las fotos que tienen, y durante la correccion no va a ser probado con
otras fotos. Saludos.

**Comment by rogelio-alb** [comment]
Hola Profesor, en los cálculos del error, según entiendo la hora de referencia la debemos establecer nosotros con anterioridad y luego contrastarla con lo obtenido por el programa, pero en algunas de las fotos es complicado distinguir la hora correcta en los minutos, por ejemplo en la segunda imagen no sabría decir si son las 4:09 o las 4:10, diferencia que puede ser significativa en el error total de nuestro programas. Mi pregunta es si existe alguna otra forma de calcular a priori la hora "real" de las imágenes.

Saludos !

**Comment by OdetteRi** [comment]
Hola, una pregunta. ¿Puedo hacer que el código una vez que se ejecute arroje todos los resultados de inmediato? o ¿Usted quiere ingresar la la imagen una a una, y obtener su resultado?
Espero su respuesta, 
Saludos :)

**Comment by domingomery** [comment]
como tu prefieras, solo te pido que seas claro a la hora de indicar lo que
hay que hacer con tu codigo para ayudar a lo/as ayudantes en su corrección.
Saludos

**Comment by domingomery** [comment]
La idea es que este tipo de errores no afecte tu nota, toamaré como nota
ideal la que está en este foro con +/- 1 minuto. Saludos

**Comment by Okhan97** [comment]
@domingomery 
Profesor, ¿es posible que se liberen los resultados esperados para esta tarea?
Mas arriba un compañero subió una estimación que pensé seria la correcta (o muy cercana) y sin embargo al recibir la rubrica de mi corrección me sale que tuve un error en el numero de horas (y no en el de minutos lo que me parece aún mas extraño).

**Comment by domingomery** [comment]
Cualquier duda o reclamo, por favor contacten directamente con lo/as
ayudantes y si no llegan a acuerdo por favor acudan a mi. Muchas gracias.
