### ISSUE TITLE
Output Ejercicio 1

### ISSUE THREAD

**Issue by dabalada** [domingomery/imagenes#8]
El output debe ser una imagen guardada o puede solo mostrarse en pantalla con pausas entremedio?

**Comment by domingomery** [comment]
puede ser con pausas. saludos

**Comment by Calomi** [comment]
yo hice que se guardara un archivo IMGXX_output.png para cada ejercicio, como prefiere que sea profe?

**Comment by domingomery** [comment]
me da lo mismo, lo importante es que se entienda bien lo que hicieron.
Saludos
