### ISSUE TITLE
Foro del Proyecto del Curso

### ISSUE THREAD

**Issue by domingomery** [domingomery/imagenes#9]
Escribe aquí tus comentarios o dudas sobre el proyecto del curso.

**Comment by fprebolledo** [comment]
Hola! tenía una consulta de que cosas están permitidas usar. Por ejemplo tengo entendido que hay varios algoritmos para elegir el humbral para binarizar una imagen, me preguntaba si están disponibles en alguna librería podemos utilizarlos ? o debemos programarlos?

**Comment by domingomery** [comment]
se pueden usar librerias de procesamiento de imagenes (siempre y cuando
sepan que es lo que hacen), no está permitido usar nada que tenga que ver
machine learning (porque este curso no es sobre machine learning :). Saludos

**Comment by Matias-CT** [comment]
Hola, es obligación utilizar métodos no vistos en clase en el proyecto (además de los que si vimos), ya que en un principio puede que sean sufcientes los métodos vistos en clases, al menos para idear una solución óptima.
Saludos.

**Comment by domingomery** [comment]
asi es, deben usar otros métodos también… es una buena práctica en los tiempos que vivimos (en los que hay tantos adelantos científicos y tecnológicos cada año) tener la costumbre de aprender un poco más allá de lo que se ve en clases.

Saludos

**Comment by cerealnuee** [comment]
¡Hola! Creo que sobrevivió esta línea del proyecto del año pasado en el enunciado del proyecto. Siguiendo esta línea, ¿para la demo nos pedirá segmentar 5 fotos extra?
![image](https://user-images.githubusercontent.com/34427488/99889415-9e8e1d00-2c33-11eb-9df5-1b231e9a7b64.png)

**Comment by alejita97** [comment]
Profesor, si construimos una función debemos usar los mismos parámetros para todas las imágenes o podemos cambiar los parámetros para cada una de las **50** imágenes.
 De antemano muchas gracias :)

**Comment by domingomery** [comment]
> ¡Hola! Creo que sobrevivió esta línea del proyecto del año pasado en el enunciado del proyecto. Siguiendo esta línea, ¿para la demo nos pedirá segmentar 5 fotos extra?
> ![image](https://user-images.githubusercontent.com/34427488/99889415-9e8e1d00-2c33-11eb-9df5-1b231e9a7b64.png)

jajaja... se me fue el copy paste... :)  actualice el enunciado con esto:

"Adicionalmente, deben realizar la segmentacion en 5 imagenes nuevas de lunares (muy similares a la de esta base de datos de 50) que el profesor proporcionara en el momento de la demo. Para la evaluacion de estas 5 imagenes se cuenta tambien con la segmentacion ideal, que sera usada para que calculen el TPR y FPR."

**Comment by domingomery** [comment]
> Profesor, si construimos una función debemos usar los mismos parámetros para todas las imágenes o podemos cambiar los parámetros para cada una de las **50** imágenes.
> De antemano muchas gracias :)

Es una sola funcion. Existen soluciones en que la misma funcion adapta internamente los parametros (de manera automatica), por ejemplo si la imagen es muy oscura entonces el threshold de la segmentacion baja en 10%...

Deben desarrollar una sola funcion, no 50.

**Comment by domingomery** [comment]
He implementado en Python el método de segmentación de imagenes a color visto en clases que utiliza la conversion RGB a una  imagen en tonos de gris de alto contraste (ver [video](https://youtu.be/FeZnQdgrX9c) a partir del minuto 23:22)

Codigo en [Google Colab](https://colab.research.google.com/drive/1008PCfxNSjuvpYSDHg1gRAY9oySIzyYk?usp=sharing)

**Comment by jvlara** [comment]
Profesor, si ocupamos un metodo de cv2 que ocupa un algoritmo con tecnicas bastante complejas (en especifico findContours de cv2 con el algoritmo de susuki) ¿es necesario saber en especifico como funciona esta implementación?

**Comment by domingomery** [comment]
no en detalle, pero si conceptualmente

Saludos

**Comment by fnquinteros** [comment]
Tiene sentido calcular el error utilizando solamente los pixeles blancos? Eso hace que cualquier error se note más, porque las segmentaciones que he hecho son suficientemente similares a la ideal como para que tenga muchos pixeles negros en común, por lo que si considerara toda la imagen para el calculo del error, el porcentaje de error disminuiría, pero siento que sería medio falso ese porcentaje de error, por que me interesa que los pixeles blancos (la segmentación) sea lo más parecida posible a la ideal.

**Comment by domingomery** [comment]
buen comentario... hay muchas formas de estimar el error, una forma clasica es calcular las variables "precision" y "recall" que tiene mucho que ver con lo que dices ya que no considera los falsos negativos... si uds quieren calculen estos valores de manera opcional (las definiciones se encuentran en wikipedia por ejemplo), pero para la tarea deben calcular las variables del enunciado (no porque sean mejores, sino porque asi todos los grupos calculan lo mismo y podemos comparar los desempeños de los algoritmos desarrollados).

Saludos

**Comment by domingomery** [comment]
En la presentacion final deben calcular adicionalemente el F1-score definido como:

F1 = TT / (TT + FP + FN) donde TT = 2 x TP

**Comment by Matias-CT** [comment]
Hola profe :) 
Quería preguntarle que tanto detalle debe haber en 'la revisión del estado del arte' en la presentación.
¿Hay que presentar alguna serie de papers? ¿o con uno reciente basta para abordar esa sección (por ejemplo, en las introducciones de los papers siempre se habla del estado del arte ¿con basarnos en la intro de uno bastaría?) ?
Saludos

**Comment by domingomery** [comment]
yo espero que lean al menos tres papers sobre metodos de segmentacion de
lunares, en que el fuerte del paper sea procesamiento de imagenes (y no
machine learning)... el objetivo es que estos papers no solo sean usados
para saber en que está el estado del arte, sino que tambien para entender
nuevos metodos, y que algunas de las ideas de estos metodos puedan usarlas
en el metodo propuesto por uds.

On Wed, Dec 9, 2020 at 10:07 PM Matias-CT <notifications@github.com> wrote:
>
> Hola profe :)
> Quería preguntarle que tanto detalle debe haber en 'la revisión del
estado del arte' en la presentación.
> ¿Hay que presentar alguna serie de papers? ¿o con uno reciente basta para
abordar esa sección (por ejemplo, en las introducciones de los papers
siempre se habla del estado del arte ¿con basarnos en la intro de uno
bastaría?) ?
